import type { User } from "../../types/auth"
import type { Topic, TopicRevision } from "../../types/topics"
import type { ProgressMilestone } from "../../types/progress"
import type { Submission } from "../../types/submission"
import type { Review } from "../../types/review"
import type { ScheduleEvent } from "../../types/schedule"
import type { Rubric, ScoreSheet, FinalScore } from "../../types/scoring"
import type { Notification } from "../../types/notification"

export const seedData = {
  users: [
    {
      id: "user_admin",
      email: "admin@university.edu.vn",
      name: "Quản trị viên",
      role: "ADMIN",
      profile: {
        department: "IT",
        faculty: "Công nghệ thông tin",
        phone: "0123456789",
      },
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "user_hod",
      email: "hod@university.edu.vn",
      name: "PGS.TS Nguyễn Văn A",
      role: "HOD",
      profile: {
        department: "IT",
        faculty: "Công nghệ thông tin",
        phone: "0123456790",
      },
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "user_supervisor_1",
      email: "supervisor1@university.edu.vn",
      name: "TS. Trần Thị B",
      role: "SUPERVISOR",
      profile: {
        department: "IT",
        faculty: "Công nghệ thông tin",
        phone: "0123456791",
      },
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "user_supervisor_2",
      email: "supervisor2@university.edu.vn",
      name: "ThS. Lê Văn C",
      role: "SUPERVISOR",
      profile: {
        department: "IT",
        faculty: "Công nghệ thông tin",
        phone: "0123456792",
      },
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "user_reviewer_1",
      email: "reviewer1@university.edu.vn",
      name: "TS. Phạm Văn D",
      role: "REVIEWER",
      profile: {
        department: "IT",
        faculty: "Công nghệ thông tin",
        phone: "0123456793",
      },
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "user_reviewer_2",
      email: "reviewer2@university.edu.vn",
      name: "TS. Hoàng Thị E",
      role: "REVIEWER",
      profile: {
        department: "IT",
        faculty: "Công nghệ thông tin",
        phone: "0123456794",
      },
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "user_council_chair",
      email: "chair@university.edu.vn",
      name: "PGS.TS Vũ Văn F",
      role: "COUNCIL_CHAIR",
      profile: {
        department: "IT",
        faculty: "Công nghệ thông tin",
        phone: "0123456795",
      },
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "user_student_1",
      email: "student1@student.university.edu.vn",
      name: "Nguyễn Văn Nam",
      role: "STUDENT",
      profile: {
        studentId: "20210001",
        department: "IT",
        faculty: "Công nghệ thông tin",
        phone: "0123456796",
      },
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "user_student_2",
      email: "student2@student.university.edu.vn",
      name: "Trần Thị Lan",
      role: "STUDENT",
      profile: {
        studentId: "20210002",
        department: "IT",
        faculty: "Công nghệ thông tin",
        phone: "0123456797",
      },
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "user_student_3",
      email: "student3@student.university.edu.vn",
      name: "Lê Văn Minh",
      role: "STUDENT",
      profile: {
        studentId: "20210003",
        department: "IT",
        faculty: "Công nghệ thông tin",
        phone: "0123456798",
      },
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
  ] as User[],

  topics: [
    {
      id: "topic_1",
      title: "Xây dựng hệ thống quản lý thư viện sử dụng React và Node.js",
      description:
        "Phát triển một hệ thống quản lý thư viện hoàn chỉnh với các chức năng: quản lý sách, quản lý độc giả, mượn/trả sách, thống kê báo cáo.",
      status: "IN_PROGRESS",
      studentId: "user_student_1",
      supervisorId: "user_supervisor_1",
      reviewerIds: ["user_reviewer_1", "user_reviewer_2"],
      department: "IT",
      faculty: "Công nghệ thông tin",
      academicYear: "2024-2025",
      defenseType: "COUNCIL",
      createdAt: "2024-09-01T00:00:00Z",
      updatedAt: "2024-11-15T00:00:00Z",
    },
    {
      id: "topic_2",
      title: "Ứng dụng AI trong phân tích cảm xúc từ văn bản tiếng Việt",
      description: "Nghiên cứu và xây dựng mô hình AI để phân tích cảm xúc từ các văn bản tiếng Việt trên mạng xã hội.",
      status: "APPROVED",
      studentId: "user_student_2",
      supervisorId: "user_supervisor_2",
      reviewerIds: [],
      department: "IT",
      faculty: "Công nghệ thông tin",
      academicYear: "2024-2025",
      createdAt: "2024-09-15T00:00:00Z",
      updatedAt: "2024-10-01T00:00:00Z",
    },
    {
      id: "topic_3",
      title: "Hệ thống thương mại điện tử với tích hợp thanh toán online",
      description:
        "Xây dựng website thương mại điện tử hoàn chỉnh với các tính năng: quản lý sản phẩm, giỏ hàng, thanh toán online, quản lý đơn hàng.",
      status: "PENDING",
      studentId: "user_student_3",
      supervisorId: "user_supervisor_1",
      reviewerIds: [],
      department: "IT",
      faculty: "Công nghệ thông tin",
      academicYear: "2024-2025",
      createdAt: "2024-11-01T00:00:00Z",
      updatedAt: "2024-11-01T00:00:00Z",
    },
  ] as Topic[],

  topicRevisions: [
    {
      id: "revision_1",
      topicId: "topic_1",
      version: 1,
      title: "Xây dựng hệ thống quản lý thư viện sử dụng React và Node.js",
      description: "Phát triển một hệ thống quản lý thư viện hoàn chỉnh với các chức năng cơ bản.",
      changes: "Bổ sung chi tiết về các chức năng thống kê báo cáo",
      note: "Cần làm rõ hơn về phần thống kê và báo cáo",
      createdBy: "user_hod",
      createdAt: "2024-09-10T00:00:00Z",
    },
  ] as TopicRevision[],

  progressMilestones: [
    {
      id: "milestone_1",
      topicId: "topic_1",
      type: "OUTLINE",
      title: "Đề cương chi tiết",
      description: "Hoàn thành đề cương chi tiết của khóa luận",
      deadline: "2024-10-15T00:00:00Z",
      status: "COMPLETED",
      feedback: "Đề cương được làm tốt, có thể tiến hành thực hiện",
      completedAt: "2024-10-10T00:00:00Z",
      createdAt: "2024-09-01T00:00:00Z",
      updatedAt: "2024-10-10T00:00:00Z",
    },
    {
      id: "milestone_2",
      topicId: "topic_1",
      type: "CHAPTER_1",
      title: "Chương 1: Tổng quan",
      description: "Hoàn thành chương 1 về tổng quan lý thuyết",
      deadline: "2024-11-15T00:00:00Z",
      status: "IN_PROGRESS",
      createdAt: "2024-10-15T00:00:00Z",
      updatedAt: "2024-11-01T00:00:00Z",
    },
    {
      id: "milestone_3",
      topicId: "topic_1",
      type: "CHAPTER_2",
      title: "Chương 2: Phân tích thiết kế",
      description: "Hoàn thành chương 2 về phân tích và thiết kế hệ thống",
      deadline: "2024-12-15T00:00:00Z",
      status: "PENDING",
      createdAt: "2024-11-15T00:00:00Z",
      updatedAt: "2024-11-15T00:00:00Z",
    },
  ] as ProgressMilestone[],

  submissions: [
    {
      id: "submission_1",
      topicId: "topic_1",
      type: "CHAPTER",
      version: 1,
      fileName: "chuong1_v1.pdf",
      fileSize: 2048576,
      fileUrl: "/uploads/chuong1_v1.pdf",
      note: "Bản nháp chương 1",
      uploadedBy: "user_student_1",
      uploadedAt: "2024-11-01T00:00:00Z",
    },
    {
      id: "submission_2",
      topicId: "topic_1",
      type: "CHAPTER",
      version: 2,
      fileName: "chuong1_v2.pdf",
      fileSize: 2150000,
      fileUrl: "/uploads/chuong1_v2.pdf",
      note: "Chương 1 sau khi sửa theo góp ý",
      uploadedBy: "user_student_1",
      uploadedAt: "2024-11-10T00:00:00Z",
    },
  ] as Submission[],

  reviews: [
    {
      id: "review_1",
      topicId: "topic_1",
      reviewerId: "user_reviewer_1",
      type: "REVIEWER_1",
      status: "PASS",
      score: 8.5,
      comments: "Đề tài có tính khả thi cao, sinh viên thể hiện hiểu biết tốt về vấn đề.",
      createdAt: "2024-11-05T00:00:00Z",
      updatedAt: "2024-11-05T00:00:00Z",
    },
    {
      id: "review_2",
      topicId: "topic_1",
      reviewerId: "user_reviewer_2",
      type: "REVIEWER_2",
      status: "PASS",
      score: 8.0,
      comments: "Nội dung tốt, cần bổ sung thêm một số tài liệu tham khảo.",
      createdAt: "2024-11-06T00:00:00Z",
      updatedAt: "2024-11-06T00:00:00Z",
    },
  ] as Review[],

  scheduleEvents: [
    {
      id: "event_1",
      title: "Báo cáo thử - Nhóm 1",
      description: "Báo cáo tiến độ thực hiện khóa luận",
      type: "TRIAL_PRESENTATION",
      startTime: "2024-12-01T09:00:00Z",
      endTime: "2024-12-01T11:00:00Z",
      location: "Phòng 301 - Tòa A",
      topicIds: ["topic_1"],
      participantIds: ["user_student_1", "user_supervisor_1", "user_reviewer_1"],
      createdBy: "user_supervisor_1",
      createdAt: "2024-11-15T00:00:00Z",
    },
    {
      id: "event_2",
      title: "Hội đồng bảo vệ khóa luận",
      description: "Bảo vệ khóa luận tốt nghiệp",
      type: "COUNCIL_DEFENSE",
      startTime: "2024-12-20T14:00:00Z",
      endTime: "2024-12-20T16:00:00Z",
      location: "Hội trường A",
      topicIds: ["topic_1"],
      participantIds: ["user_student_1", "user_council_chair", "user_reviewer_1", "user_reviewer_2"],
      createdBy: "user_hod",
      createdAt: "2024-11-20T00:00:00Z",
    },
  ] as ScheduleEvent[],

  rubrics: [
    {
      id: "rubric_supervisor",
      name: "Rubric đánh giá của GVHD",
      type: "SUPERVISOR",
      criteria: [
        {
          id: "criteria_1",
          name: "Thái độ học tập",
          description: "Đánh giá thái độ học tập và nghiên cứu của sinh viên",
          maxScore: 2,
          weight: 0.2,
        },
        {
          id: "criteria_2",
          name: "Khả năng nghiên cứu",
          description: "Khả năng tìm hiểu, nghiên cứu tài liệu",
          maxScore: 3,
          weight: 0.3,
        },
        {
          id: "criteria_3",
          name: "Kết quả thực hiện",
          description: "Chất lượng sản phẩm, kết quả đạt được",
          maxScore: 5,
          weight: 0.5,
        },
      ],
      maxScore: 10,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
    {
      id: "rubric_reviewer",
      name: "Rubric đánh giá của GVPB",
      type: "REVIEWER",
      criteria: [
        {
          id: "criteria_4",
          name: "Tính mới và sáng tạo",
          description: "Mức độ mới mẻ và sáng tạo của đề tài",
          maxScore: 3,
          weight: 0.3,
        },
        {
          id: "criteria_5",
          name: "Tính khả thi",
          description: "Khả năng thực hiện được của đề tài",
          maxScore: 3,
          weight: 0.3,
        },
        {
          id: "criteria_6",
          name: "Chất lượng báo cáo",
          description: "Chất lượng báo cáo khóa luận",
          maxScore: 4,
          weight: 0.4,
        },
      ],
      maxScore: 10,
      isActive: true,
      createdAt: "2024-01-01T00:00:00Z",
      updatedAt: "2024-01-01T00:00:00Z",
    },
  ] as Rubric[],

  scoreSheets: [
    {
      id: "score_1",
      topicId: "topic_1",
      rubricId: "rubric_supervisor",
      scorerId: "user_supervisor_1",
      type: "SUPERVISOR",
      scores: [
        { criteriaId: "criteria_1", score: 1.8 },
        { criteriaId: "criteria_2", score: 2.7 },
        { criteriaId: "criteria_3", score: 4.2 },
      ],
      totalScore: 8.7,
      comments: "Sinh viên làm việc nghiêm túc, kết quả đạt yêu cầu.",
      createdAt: "2024-11-15T00:00:00Z",
      updatedAt: "2024-11-15T00:00:00Z",
    },
  ] as ScoreSheet[],

  finalScores: [
    {
      id: "final_1",
      topicId: "topic_1",
      supervisorScore: 8.7,
      reviewerScore: 8.3,
      councilScore: 8.5,
      finalScore: 8.5,
      bonusScore: 0.5,
      totalScore: 9.0,
      bonusReason: "Đề tài có tính ứng dụng cao, được đánh giá tốt",
      calculatedAt: "2024-12-01T00:00:00Z",
      calculatedBy: "user_hod",
    },
  ] as FinalScore[],

  notifications: [
    {
      id: "notif_1",
      userId: "user_student_1",
      type: "DEADLINE_REMINDER",
      title: "Nhắc nhở deadline",
      message: "Bạn có deadline nộp chương 2 vào ngày 15/12/2024",
      data: { topicId: "topic_1", milestoneId: "milestone_3" },
      isRead: false,
      createdAt: "2024-11-20T00:00:00Z",
    },
    {
      id: "notif_2",
      userId: "user_student_1",
      type: "SCHEDULE_UPDATE",
      title: "Lịch báo cáo thử",
      message: "Lịch báo cáo thử của bạn đã được xếp vào ngày 01/12/2024",
      data: { eventId: "event_1" },
      isRead: true,
      createdAt: "2024-11-15T00:00:00Z",
    },
    {
      id: "notif_3",
      userId: "user_student_1",
      type: "REVIEW_ASSIGNED",
      title: "Phân công phản biện",
      message: "Đề tài của bạn đã được phân công cho TS. Phạm Văn D phản biện",
      data: { topicId: "topic_1", reviewerId: "user_reviewer_1" },
      isRead: false,
      createdAt: "2024-11-18T00:00:00Z",
    },
    {
      id: "notif_4",
      userId: "user_student_1",
      type: "SCORE_UPDATED",
      title: "Cập nhật điểm số",
      message: "Giảng viên hướng dẫn đã chấm điểm cho đề tài của bạn: 8.7/10",
      data: { topicId: "topic_1", scoreId: "score_1" },
      isRead: false,
      createdAt: "2024-11-16T00:00:00Z",
    },
    {
      id: "notif_5",
      userId: "user_student_1",
      type: "STATUS_CHANGED",
      title: "Thay đổi trạng thái đề tài",
      message: "Trạng thái đề tài của bạn đã được cập nhật thành 'Đang thực hiện'",
      data: { topicId: "topic_1", oldStatus: "APPROVED", newStatus: "IN_PROGRESS" },
      isRead: true,
      createdAt: "2024-11-10T00:00:00Z",
    },
    {
      id: "notif_6",
      userId: "user_supervisor_1",
      type: "CHAT_MESSAGE",
      title: "Tin nhắn mới",
      message: "Sinh viên Nguyễn Văn Nam đã gửi tin nhắn cho bạn",
      data: { topicId: "topic_1", senderId: "user_student_1" },
      isRead: false,
      createdAt: "2024-11-19T00:00:00Z",
    },
  ] as Notification[],
}
